image:
  imagePullPolicy: IfNotPresent
  container: registry.gitlab.com/ska-telescope/ost/templates/ska-ost-osd-ui/ska-ost-osd-ui
  version: 0.1.0

labels:
  app: ska-ost-osd-ui

ingress:
  prependByNamespace: true
