apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "ska-ost-osd-ui.labels" . | indent 4 }}
data:
  BACKEND_URL: {{ .Values.backendURL }}
  BASE_URL: /{{ .Release.Namespace }}/osd
