apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}
  labels:
{{ include "ska-ost-osd-ui.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name }}
  template:
    metadata:
      labels:
{{ include "ska-ost-osd-ui.labels" . | indent 8 }}
      annotations:
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.registry }}/{{ .Values.image.image }}:{{$.Values.image.tag | default $.Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          env:
            - name: REACT_APP_USE_LOCAL_DATA
              value: {{ .Values.runtimeEnv.useLocalData | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: {{ $.Chart.Name }}-nginx-config

